name: Deploy

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

env:
  AWS_REGION: eu-west-1
  DEPLOY_ROLE_ARN: arn:aws:iam::703775540847:role/waste-schedule-scraper-deploy-role

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: ${{ env.DEPLOY_ROLE_ARN }}
          role-ression-name: deploy-waste-session
          aws-region: ${{ env.AWS_REGION }}

      - name: set creds as tf variables
        run: |
          touch tf/creds.tfvars
          echo access_key_id="$AWS_ACCESS_KEY_ID" >> tf/creds.tfvars
          cat tf/creds.tfvars
          #echo secret_access_key="$SECRET_KEY" >> tf/creds.tfvars
          #echo session_token="$SESSION_TOKEN" >> tf/creds.tfvars
        env:
          ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
          SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          # terraform_version: 0.13.0:
          cli_config_credentials_token: ${{ secrets.TERRAFORM_API_TOKEN }}

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Plan
        run: terraform plan -no-color -var-file="tf/creds.tfvars"
